gui:
  theme:
    activeBorderColor:
      - "#ddc7a1"
      - bold
    inactiveBorderColor:
      - "#928374"
    optionsTextColor:
      - "#d8a657"
    selectedLineBgColor:
      - "#504945"
    cherryPickedCommitBgColor:
      - "#504945"
    cherryPickedCommitFgColor:
      - "#e78a4e"
      - bold
      - reverse
    unstagedChangesColor:
      - "#ea6962"
    defaultFgColor:
      - "#d4be98"
    searchingActiveBorderColor:
      - "#ea6962"
  nerdFontsVersion: "3"
  showFileIcons: true
