-- TODO:
-- map_set({ 'n' }, '>p', '<plug>(YankyPutIndentAfterShiftRight)')
-- map_set({ 'n' }, '<p', '<plug>(YankyPutIndentAfterShiftLeft)')
-- map_set({ 'n' }, '>P', '<plug>(YankyPutIndentBeforeShiftRight)')
-- map_set({ 'n' }, '<P', '<plug>(YankyPutIndentBeforeShiftLeft)')
-- map_set({ 'n' }, '=p', '<plug>(YankyPutAfterFilter)')
-- map_set({ 'n' }, '=P', '<plug>(YankyPutBeforeFilter)')
-- map_set('n', '<c-p>', '<plug>(YankyPreviousEntry)')
-- map_set('n', '<c-n>', '<plug>(YankyNextEntry)')
