keymap:
  - name: "Not wezterm"
    application:
      not: "org.wezfurlong.wezterm"
    remap:
      Ctrl-a: Home
      Ctrl-e: End
      Alt-z: Ctrl-z
      Alt-x: Ctrl-x
      Alt-c: Ctrl-c
      Alt-v: Ctrl-v
      Alt-a: Ctrl-a
      Alt-f: Ctrl-f
