require('core')
require('key_mapping')
require('markdown_support')
require('line_wise')
require('package_manager')
require('lazy').setup({ spec = require('plugins') })
require('utils').start_to_check_network()
